version: 0.1

phases:
  pre-build:
    commands:
      - npm ci
      - npm test
  build:
    commands:
      - npm run wpp
artifacts:
  files:
    - index.html
    - favicon.ico
    - Profile.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
